version: '2'
services:
  appcues:
    build: .
    depends_on:
      - "postgres"
    hostname: appcues
  postgres:
    image: "sfackler/rust-postgres-test:6"
    ports:
      - 5433:5433
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - appcues
    ports:
      - "3333:3333"